version: "3.8"

services:
  online-shop:
    container_name: online-shop-container
    build: 
       context: .
       dockerfile: Dockerfile
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"] 
      interval: 40s
      timeout: 10s
      retries: 3
      start_period: 60s

    restart: always
