# Base image of Node js
FROM node:20-alpine AS build

# setting up working directory
WORKDIR /app

# Copying the necessary packages
COPY package*.json ./

# ci -> Clean Install the dependencies
RUN npm ci 

# Copying the source code
COPY . .

# building the project 
RUN npm run build


# ---------- STAGE 2 -------------

# using Distroless Base image
FROM gcr.io/distroless/nodejs20-debian12

#  working directory
WORKDIR /app

# Copying the build that have created in the stage 1
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000

CMD ["./node_modules/.bin/serve", "-s", "dist", "-l", "3000"]
