sonar.projectKey=online-shop-key
sonar.projectName=online-shop-app
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://3.6.86.193:9100
sonar.login=squ_736bf210416e622c9b5517ea0fed8b9280aad05d

